default: &default
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ezlite_dev
  username: root
  password:

test:
  <<: *default
  database: ezlite_test
  username: root
  password:

production:
  <<: *default
  database: ezlite_pro
  username: root
  password: